### PR TITLE
Added support for only copying partitions, plus using libctr9_io

### PR DESCRIPTION
**Pull request by gemarcano**

### CODE REVIEW

**Comment by gemarcano** [comment]
Checks failed  due to travis-ci environment missing libctr9_io.

**Comment by gemarcano** [comment]
Please ignore. This is meant to be for my fork.

**Comment by neobrain** [comment]
Are you planning on contributing back these changes in some form regardless at some point?

**Comment by gemarcano** [comment]
I do. Not sure if you want to use my IO lib. Anyhow, those would be two separate pull requests. I'd like to clean up some of the trimming support stuff before I submit.

**Comment by neobrain** [comment]
Fair enough, thanks!

**Pull request closed without merging**
