### PR TITLE
Add support for on-the-fly decryption.

### PR DESCRIPTION
**Pull request by linkmauve**
Supersedes PR #7, but refer to it for the actual description. ^^

I haven’t actually tested this PR yet, but will do shortly.

### CODE REVIEW

**Comment by linkmauve** [comment]
I just tested with CN, and there is too much entropy everywhere compared to what I was expecting. :/

**Comment by neobrain** [comment]
Have you checked whether the original PR works for you? If not, how about performing a raw dump and then decrypting manually using Decrypt9+xorer?

**Comment by Lectem** [comment]
The games decrypted on-the-fly wont boot with citra, tested with both CubicNinja and Zelda A link between worlds. O3DS 9.2

**Comment by Subv** [comment]
Sooo, it's been a few months, what's the status of this?

**Comment by linkmauve** [comment]
Abandonned.

**Pull request closed without merging**
